import type { Application, Request, Response } from "express";
import { z } from "zod";
import { requireAdmin } from "./auth.js";
import { approveEligibilityReview,createEligibilityReview,getEligibilityReview,listEligibilityReviews,rejectEligibilityReview } from "./eligibility-review.js";

const one=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]:value||"";
function fail(res:Response,error:unknown){const status=typeof error==="object"&&error&&"status" in error?Number((error as {status:unknown}).status):500;const payload:Record<string,unknown>={error:error instanceof Error?error.message:"Erro interno"};if(typeof error==="object"&&error&&"decision" in error)payload.decision=(error as {decision:unknown}).decision;if(typeof error==="object"&&error&&"review" in error)payload.review=(error as {review:unknown}).review;return res.status(Number.isFinite(status)&&status>=400&&status<=599?status:500).json(payload);}
const proposalSchema=z.object({
  claimCategory:z.enum(["voluntary_offset","climate_contribution","ecological_contribution","compliance","historical"]).optional(),eligibilityStatus:z.enum(["eligible","restricted","ineligible","under_review"]).optional(),eligibilityBasis:z.string().max(5000).nullable().optional(),sourceUnitStatus:z.enum(["tradable","retired","cancelled","suspended","unknown"]).optional(),
  vintageStart:z.string().date().nullable().optional(),vintageEnd:z.string().date().nullable().optional(),issuanceDate:z.string().date().nullable().optional(),commercialValidUntil:z.string().date().nullable().optional(),offerExpiresAt:z.string().datetime().nullable().optional(),registryProjectId:z.string().max(180).nullable().optional(),registryBatchId:z.string().max(255).nullable().optional(),registryEvidenceUrl:z.string().url().nullable().optional(),
  retirementSupported:z.boolean().optional(),fractionalRetirementSupported:z.boolean().optional(),retirementGranularityKg:z.coerce.number().int().positive().max(1_000_000).optional(),beneficiaryRetirementSupported:z.boolean().optional(),ccpStatus:z.enum(["approved","eligible_program","not_approved","not_assessed"]).optional(),corsiaStatus:z.enum(["eligible","authorized","not_eligible","not_assessed"]).optional(),article6Status:z.enum(["eligible","authorized","not_eligible","not_assessed"]).optional(),vintagePolicyOverride:z.boolean().optional(),vintageExceptionReason:z.string().max(3000).nullable().optional(),riskFlags:z.array(z.string().max(120)).max(30).optional(),
});

export function registerEligibilityReviewRoutes(app:Application){
  app.get("/api/admin/market/eligibility-reviews",requireAdmin,async(req:Request,res:Response)=>{try{const items=await listEligibilityReviews({status:String(req.query.status||""),assetId:Number(req.query.assetId||0),limit:Number(req.query.limit||100)});res.setHeader("Cache-Control","no-store");return res.json({count:items.length,items});}catch(error){return fail(res,error);}});
  app.get("/api/admin/market/eligibility-reviews/:id",requireAdmin,async(req:Request,res:Response)=>{try{const item=await getEligibilityReview(Number(one(req.params.id)));if(!item)return res.status(404).json({error:"Eligibility Review não encontrada"});res.setHeader("Cache-Control","no-store");return res.json(item);}catch(error){return fail(res,error);}});
  app.post("/api/admin/market/assets/:id/eligibility-reviews",requireAdmin,async(req:Request,res:Response)=>{const parsed=z.object({purpose:z.enum(["voluntary_offset","climate_contribution","ecological_contribution","compliance"]).optional(),createdBy:z.string().min(2).max(255).nullable().optional(),note:z.string().max(10000).nullable().optional(),proposal:proposalSchema}).safeParse(req.body||{});if(!parsed.success)return res.status(400).json({error:"Eligibility Review inválida",details:parsed.error.flatten()});try{return res.status(201).json(await createEligibilityReview({assetId:Number(one(req.params.id)),proposal:parsed.data.proposal,purpose:parsed.data.purpose,createdBy:parsed.data.createdBy,note:parsed.data.note}));}catch(error){return fail(res,error);}});
  app.post("/api/admin/market/eligibility-reviews/:id/approve",requireAdmin,async(req:Request,res:Response)=>{const parsed=z.object({reviewedBy:z.string().min(2).max(255).nullable().optional(),note:z.string().max(10000).nullable().optional()}).safeParse(req.body||{});if(!parsed.success)return res.status(400).json({error:"Aprovação de Eligibility Review inválida"});try{return res.json(await approveEligibilityReview({reviewId:Number(one(req.params.id)),...parsed.data}));}catch(error){return fail(res,error);}});
  app.post("/api/admin/market/eligibility-reviews/:id/reject",requireAdmin,async(req:Request,res:Response)=>{const parsed=z.object({reason:z.string().min(2).max(10000),reviewedBy:z.string().min(2).max(255).nullable().optional()}).safeParse(req.body||{});if(!parsed.success)return res.status(400).json({error:"Rejeição de Eligibility Review inválida",details:parsed.error.flatten()});try{return res.json(await rejectEligibilityReview({reviewId:Number(one(req.params.id)),...parsed.data}));}catch(error){return fail(res,error);}});
}
