import type { Application,NextFunction,Request,Response } from "express";
import { z } from "zod";
import { requireAdmin } from "./auth.js";
import { pool } from "./db.js";
import { assetProjection } from "./market-db.js";
import { refreshIfStale,refreshMarketData } from "./market-refresh.js";

const statuses=["requested","reviewing","quoted","awaiting_payment","sourcing","retired","delivered","cancelled"] as const;
const assetSchema=z.object({registry:z.string().min(2).max(120),projectName:z.string().min(3).max(255),sourceReference:z.string().min(2).max(180),sourceUrl:z.string().url().nullable().optional(),methodology:z.string().max(255).nullable().optional(),location:z.string().max(255).nullable().optional(),vintage:z.string().max(40).nullable().optional(),assetType:z.string().min(2).max(40).default("carbon"),qualityTier:z.string().min(2).max(40).default("screening"),description:z.string().max(5000).nullable().optional(),sourcePriceUsdTon:z.coerce.number().positive().nullable().optional(),fxBrlUsd:z.coerce.number().positive().default(5.5),serviceMarginPct:z.coerce.number().min(0).max(500).default(25),fixedFeeBrl:z.coerce.number().min(0).default(0),availableTons:z.coerce.number().min(0).nullable().optional(),minOrderKg:z.coerce.number().int().positive().default(100),pricingMode:z.enum(["quote","dynamic"]).default("quote"),availabilityStatus:z.enum(["monitoring","indicative","confirmed"]).default("monitoring"),sourceStatus:z.enum(["manual","connected","degraded"]).default("manual"),active:z.boolean().default(true)});
type AssetInput=z.infer<typeof assetSchema>;
const values=(d:AssetInput)=>[d.registry,d.projectName,d.sourceReference,d.sourceUrl||null,d.methodology||null,d.location||null,d.vintage||null,d.assetType,d.qualityTier,d.description||null,d.sourcePriceUsdTon??null,d.fxBrlUsd,d.serviceMarginPct,d.fixedFeeBrl,d.availableTons??null,d.minOrderKg,d.pricingMode,d.availabilityStatus,d.sourceStatus,d.active];
const fail=(res:Response,e:unknown)=>res.status(500).json({error:e instanceof Error?e.message:"Erro interno"});
const calc=(a:Record<string,unknown>,kg:number)=>{if(a.source_price_usd_ton==null)return {price:null,total:null};const ton=Number(a.source_price_usd_ton)*Number(a.fx_brl_usd)*(1+Number(a.service_margin_pct)/100)+Number(a.fixed_fee_brl);return {price:ton/1000,total:ton*kg/1000};};

export function registerMarketRoutes(app:Application){
  app.get("/api/market/assets",async(_req:Request,res:Response)=>{refreshIfStale();try{const {rows}=await pool.query(`SELECT ${assetProjection} FROM monitored_assets a WHERE a.active=TRUE ORDER BY CASE a.availability_status WHEN 'confirmed' THEN 1 WHEN 'indicative' THEN 2 ELSE 3 END,a.updated_at DESC`);res.json(rows);}catch(e){fail(res,e);}});
  app.post("/api/market/quotes",async(req:Request,res:Response)=>{
    const p=z.object({assetId:z.coerce.number().int().positive(),buyerName:z.string().min(2).max(255),buyerEmail:z.string().email(),buyerPhone:z.string().max(40).optional(),companyName:z.string().max(255).optional(),taxId:z.string().max(40).optional(),requestedKg:z.coerce.number().int().positive().max(10000000),deliveryMode:z.enum(["email","wallet"]).default("email"),walletAddress:z.string().max(100).optional(),purpose:z.string().max(120).default("neutralization")}).safeParse(req.body);
    if(!p.success)return res.status(400).json({error:"Dados da cotação inválidos",details:p.error.flatten()});
    if(p.data.deliveryMode==="wallet"&&!/^0x[a-fA-F0-9]{40}$/.test(p.data.walletAddress||""))return res.status(400).json({error:"Informe um endereço 0x válido"});
    try{
      const ar=await pool.query("SELECT * FROM monitored_assets WHERE id=$1 AND active=TRUE",[p.data.assetId]);const a=ar.rows[0];
      if(!a)return res.status(404).json({error:"Ativo monitorado não encontrado"});
      if(p.data.requestedKg<Number(a.min_order_kg))return res.status(400).json({error:`Pedido mínimo: ${a.min_order_kg} kg`});
      const estimate=calc(a,p.data.requestedKg);
      const {rows}=await pool.query(`INSERT INTO quote_requests(asset_id,buyer_name,buyer_email,buyer_phone,company_name,tax_id,requested_kg,delivery_mode,wallet_address,purpose,indicative_price_per_kg,indicative_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING public_code,status,requested_kg,indicative_price_per_kg,indicative_total,created_at`,[p.data.assetId,p.data.buyerName,p.data.buyerEmail,p.data.buyerPhone||null,p.data.companyName||null,p.data.taxId||null,p.data.requestedKg,p.data.deliveryMode,p.data.walletAddress||null,p.data.purpose,estimate.price,estimate.total]);
      res.status(201).json({...rows[0],asset:{id:a.id,registry:a.registry,projectName:a.project_name},message:"Solicitação registrada. Preço e disponibilidade serão confirmados antes de qualquer cobrança."});
    }catch(e){fail(res,e);}
  });
  app.get("/api/market/quotes/:publicCode",async(req:Request,res:Response)=>{try{const {rows}=await pool.query(`SELECT q.public_code,q.requested_kg,q.delivery_mode,q.indicative_total,q.final_total,q.status,q.quote_expires_at,q.created_at,q.updated_at,a.registry,a.project_name FROM quote_requests q JOIN monitored_assets a ON a.id=q.asset_id WHERE q.public_code=$1`,[req.params.publicCode]);if(!rows[0])return res.status(404).json({error:"Cotação não encontrada"});res.json(rows[0]);}catch(e){fail(res,e);}});
  app.get("/api/admin/market/assets",requireAdmin,async(_req:Request,res:Response)=>{try{const {rows}=await pool.query(`SELECT ${assetProjection} FROM monitored_assets a ORDER BY a.updated_at DESC`);res.json(rows);}catch(e){fail(res,e);}});
  app.post("/api/admin/market/assets",requireAdmin,async(req:Request,res:Response)=>{const p=assetSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:"Ativo inválido",details:p.error.flatten()});try{const {rows}=await pool.query(`INSERT INTO monitored_assets(registry,project_name,source_reference,source_url,methodology,location,vintage,asset_type,quality_tier,description,source_price_usd_ton,fx_brl_usd,service_margin_pct,fixed_fee_brl,available_tons,min_order_kg,pricing_mode,availability_status,source_status,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) RETURNING *`,values(p.data));res.status(201).json(rows[0]);}catch(e){fail(res,e);}});
  app.patch("/api/admin/market/assets/:id",requireAdmin,async(req:Request,res:Response)=>{
    const p=assetSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:"Atualização inválida",details:p.error.flatten()});
    try{const cr=await pool.query("SELECT * FROM monitored_assets WHERE id=$1",[req.params.id]);const c=cr.rows[0];if(!c)return res.status(404).json({error:"Ativo não encontrado"});const has=(k:keyof typeof p.data)=>Object.prototype.hasOwnProperty.call(p.data,k);const d=assetSchema.parse({registry:has("registry")?p.data.registry:c.registry,projectName:has("projectName")?p.data.projectName:c.project_name,sourceReference:has("sourceReference")?p.data.sourceReference:c.source_reference,sourceUrl:has("sourceUrl")?p.data.sourceUrl:c.source_url,methodology:has("methodology")?p.data.methodology:c.methodology,location:has("location")?p.data.location:c.location,vintage:has("vintage")?p.data.vintage:c.vintage,assetType:has("assetType")?p.data.assetType:c.asset_type,qualityTier:has("qualityTier")?p.data.qualityTier:c.quality_tier,description:has("description")?p.data.description:c.description,sourcePriceUsdTon:has("sourcePriceUsdTon")?p.data.sourcePriceUsdTon:c.source_price_usd_ton,fxBrlUsd:has("fxBrlUsd")?p.data.fxBrlUsd:c.fx_brl_usd,serviceMarginPct:has("serviceMarginPct")?p.data.serviceMarginPct:c.service_margin_pct,fixedFeeBrl:has("fixedFeeBrl")?p.data.fixedFeeBrl:c.fixed_fee_brl,availableTons:has("availableTons")?p.data.availableTons:c.available_tons,minOrderKg:has("minOrderKg")?p.data.minOrderKg:c.min_order_kg,pricingMode:has("pricingMode")?p.data.pricingMode:c.pricing_mode,availabilityStatus:has("availabilityStatus")?p.data.availabilityStatus:c.availability_status,sourceStatus:has("sourceStatus")?p.data.sourceStatus:c.source_status,active:has("active")?p.data.active:c.active});const {rows}=await pool.query(`UPDATE monitored_assets SET registry=$2,project_name=$3,source_reference=$4,source_url=$5,methodology=$6,location=$7,vintage=$8,asset_type=$9,quality_tier=$10,description=$11,source_price_usd_ton=$12,fx_brl_usd=$13,service_margin_pct=$14,fixed_fee_brl=$15,available_tons=$16,min_order_kg=$17,pricing_mode=$18,availability_status=$19,source_status=$20,active=$21,updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,...values(d)]);res.json(rows[0]);}catch(e){fail(res,e);}
  });
  app.post("/api/admin/market/refresh",requireAdmin,async(_req:Request,res:Response)=>{try{res.json(await refreshMarketData());}catch(e){fail(res,e);}});
  app.get("/api/admin/market/quotes",requireAdmin,async(_req:Request,res:Response)=>{try{const {rows}=await pool.query(`SELECT q.*,a.registry,a.project_name,a.source_reference FROM quote_requests q JOIN monitored_assets a ON a.id=q.asset_id ORDER BY q.created_at DESC`);res.json(rows);}catch(e){fail(res,e);}});
  app.patch("/api/admin/market/quotes/:id",requireAdmin,async(req:Request,res:Response)=>{const p=z.object({status:z.enum(statuses).optional(),finalTotal:z.coerce.number().nonnegative().nullable().optional(),quoteExpiresAt:z.string().datetime().nullable().optional(),adminNotes:z.string().max(5000).nullable().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"Atualização inválida",details:p.error.flatten()});try{const own=(k:string)=>Object.prototype.hasOwnProperty.call(p.data,k);const {rows}=await pool.query(`UPDATE quote_requests SET status=COALESCE($2,status),final_total=CASE WHEN $3::boolean THEN $4 ELSE final_total END,quote_expires_at=CASE WHEN $5::boolean THEN $6::timestamptz ELSE quote_expires_at END,admin_notes=CASE WHEN $7::boolean THEN $8 ELSE admin_notes END,updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,p.data.status||null,own("finalTotal"),p.data.finalTotal??null,own("quoteExpiresAt"),p.data.quoteExpiresAt??null,own("adminNotes"),p.data.adminNotes??null]);if(!rows[0])return res.status(404).json({error:"Cotação não encontrada"});res.json(rows[0]);}catch(e){fail(res,e);}});
}
